### ISSUE TITLE
Unexpected close tag

### ISSUE THREAD

**Issue by frecklebit** [uts-magic-lab/gulp-google-spreadsheets#1]
I'm getting the following error when using this library.

My code....

```javascript
gulp.task('fetch', () => {
  return gulpSheets(DATA.sheets)
    .pipe(gulp.dest('./src/data'));
});
```

```
[11:38:29] Error: Unexpected close tag
Line: 1256
Column: 9
Char: >
    at error (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/sax/lib/sax.js:871:9)
    at SAXParser.write (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/xml2js/lib/parser.js:5:59)
    at Request._callback (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/gulp-google-spreadsheets/node_modules/google-spreadsheet/index.js:180:20)
    at Request.self.callback (/Users/ajenkins/Code/devtools/aurora-sites/node_modules/gulp-google-spreadsheets/node_modules/request/request.js:123:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
```

**Comment by predorock** [comment]
Same error for me

**Comment by frecklebit** [comment]
Are we going to get support for this? Is there some other place we should be submitting issues?

**Comment by davidpanik** [comment]
This issue is caused by referencing an outdated version of google-spreadsheet.

The package.json for this plugin specifies version ^0.2.8 but google-spreadsheet is now up to version 2.0.4 - I'd guess at least one of those updates has been to handle a different response coming back from Google.

I manually changed to the latest version of 2.0.4 and things started working - no idea if this change will have knock-on effects elsewhere in the plugin though.
